[module]
name = "AWS Provider Module"
url = "https://github.com/rescile/aws-provider-module"
version = "0.0.5"
description = "The AWS provider module adds the configuration schemas and properties required by a landing zone blueprint to interact with and manage AWS infrastructure APIs."
rescile_version = ">=0.1.201"

# List of other modules this module depends on.
[dependencies]
landing-zone-module = "https://github.com/rescile/landing-zone-module"
